---
- name: Install MariaDB package CentOS 7
  yum: name={{ item }} state=present
  with_items:
   - mariadb-server
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- name: Install Mysql package CentOS 6
  yum: name={{ item }} state=present
  with_items:
   - mysql-server
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
   
- name: Install Mysql packages
  yum: name={{ item }} state=present
  with_items:
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf

- name: retart Mysql Service
  service: name=mysqld state=restarted enabled=yes
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
  
- name: retart Mariadb Service
  service: name=mariadb state=started enabled=yes
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'
